language: java
jdk:
- openjdk8
install: true
script: mvn clean install
cache:
  directories:
  - node_modules
  - "$HOME/.m2"
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: Fs8jx5SDudpt9eIec9S3LOjeR7hxWQeRAzrH13RhB6A2qUrNmilDN2JzvX91KrzFMBAMYhoCn4mmYGSug6YAWPO7hpvtawbqEOnJRkLdSc6o1dBKp1Y+HShvTZ3CVNbzvIwdI1KdZtgHRimKwcSJhTWUghCIVCiwTYUUCmrDkx+6eylylJpD4FR+E6WEZ6mQMa0j+OPGHvsKBpLp9TEkYcvXiwrQG2AZIiLMuZmMhlhaIhxVNKAcLmnevCYt71H5wTpvvf/qA7J83Ks2YapWWbzZQQMJolmr+fkYk3G8ZK60zjOkj4QpCxo+ohNFOT+tisYFTxswYHfEGciAdw0mxZkpo+HzRv97K3EPVHeMIGKr99Cwek9LiMyyTSGWfG9Rmcw+RV9ADFyXKfzSrWO8fBqBPaWDwDRGCCiIX7+aubYXgNCuLlJ0n5oPEPp+qnh6UJSjj5wj7FCvSlT/8PLcstgxeQmbM4ewn7PfmGbFe3JZ87h2PNjVCrEQkD3Wj89qR8E4AWKZVBgTWVfIc+uHGYfzulzwLb1QveHbf7s5+LoTfm1TG4u27uoT9YdnjZ/msqg4pyF6gbJ1yOi0I0g4jx3gtLxKbiuDCCbRtrEMHnGNfNvv/iH+qRB5gj55B3sRMh+yY8uDu3rsPJKQTr116IZnXRzMUYuiLnPMkxswpds=
  app: todo-kruemelnerd
  on:
    repo: kruemelnerd/TodoApp
