language: java

jdk:
- openjdk11

install: true
script: mvn clean install


cache:
  directories:
  - node_modules
  - $HOME/.m2

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  api_key:
    secure: "c7CvLVuJQvysXtiqQmrVGvOIro3uDD/xDBne2Zx4z37w6oY2A/sWIjHQZRjVYUfA/tFX2zF93o8M2Hp+fEXL892NL4zkRVECB6TpimqieFl4yRGLNiNpDxa+zb26KwC3i6uF3IfJxVOoMKoUjOvdbvOicIxHXtTXqYZOLhaoO4zAs7rNg1gvpPbzTbvpjpOg/Ec3CFOZoDyOCBCKLSJrBoHvEb6zgtC1h+LjzUUeccng6vECJrVvD83KtMqtMX9yU5vKEvSUm3dedqfMwZ87tmdT3FzaffBQ/4bElT/qOk2DePZLMLFgv0j+eXHqW+3gSwlOhufnHBl2vE22kjOzVW0ggXyVbs3rirulCMg55Y1VAAfOusCXnlrepgpFYihuBONSwhcasxbrkGFTvCrTmF9ajYES2j1jVEjQjh8rl5BXalFAGbTLivrpVEms33nQluXA2ApSWDzb/0uRAnDww8f7Nfeo8sa+zKvXMnFAyX/FT8TGSwK5VbT2baUdFYAbX0BEYgIgxpVJ2XdzZOim79sYGWEmBKj3V4Rzqv5cwPWMKOG+5V4kDF+HsTQ/g2MjZxmj4B+mIGzLEUC6CqF73yWH72wAEqklVEDbzjhAhNvVkkvK3zoVOs/CiOexjjKgp9Ouu4CCuTYAhIbdNCsyresZfVDUp1fJnP1+1Oo9KLk="
  app: todo-kruemelnerd
  on:
    repo: kruemelnerd/TodoApp


